// backend/testPDF.js
const puppeteer = require('puppeteer');
const fs = require('fs');

(async () => {
  const browser = await puppeteer.launch({
    headless: 'new',
    args: ['--no-sandbox']
  });

  const page = await browser.newPage();
  
  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <style>
          body { font-family: Arial; padding: 40px; }
          h1 { color: #3b82f6; }
        </style>
      </head>
      <body>
        <h1>Test PDF</h1>
        <p>This is a test PDF generated by Puppeteer!</p>
        <p>Date: ${new Date().toLocaleString()}</p>
      </body>
    </html>
  `;

  await page.setContent(html);
  
  const pdf = await page.pdf({
    format: 'A4',
    printBackground: true
  });

  fs.writeFileSync('test.pdf', pdf);
  console.log('✅ PDF saved to test.pdf');

  await browser.close();
})();